package sistemacrud_dsiii_examen_final;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.SpinnerNumberModel;

public class PanelItemResumen extends javax.swing.JPanel {
    
    private final ItemCarrito item;
    private final Cotizacion cotizacion;
    private final ViewCarrito view;
    
              
    public PanelItemResumen(ItemCarrito item, Cotizacion cotizacion, ViewCarrito view) {
        initComponents();       
        this.item = item;
        this.cotizacion = cotizacion;
        this.view = view;

        lblnombre.setText(item.getProducto().getNombre());
        lblcosto.setText(item.getCantidad() + " x $" + item.getProducto().getCosto());
        lblcodigo.setText("COD: " + item.getProducto().getId());
        if (item.getProducto().getImagen() != null && item.getProducto().getImagen().length > 0) {        
            ImageIcon icon = new ImageIcon(item.getProducto().getImagen());        
            Image img = icon.getImage().getScaledInstance(70, 70, Image.SCALE_SMOOTH);        
            lblimagen.setIcon(new ImageIcon(img));    
        } else {        
            lblimagen.setText("Sin imagen");   
        }
        spcantidad.setModel(new SpinnerNumberModel(item.getCantidad(), 0, 1000, 1));
        actualizarSubtotal();
    }    

    private void actualizarSubtotal() {
        int cantidad = (int) spcantidad.getValue();
        double subtotal = item.getProducto().getCosto() * cantidad;
        lblsubtotal.setText("$" + String.format("%.2f", subtotal));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblimagen = new javax.swing.JLabel();
        lblnombre = new javax.swing.JLabel();
        spcantidad = new javax.swing.JSpinner();
        lblsubtotal = new javax.swing.JLabel();
        lblcosto = new javax.swing.JLabel();
        lblcodigo = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(500, 90));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 223, 143), 3, true));
        jPanel1.setPreferredSize(new java.awt.Dimension(510, 90));

        lblnombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblnombre.setText("nombre");

        spcantidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spcantidadStateChanged(evt);
            }
        });

        lblsubtotal.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblsubtotal.setText("subtotal");
        lblsubtotal.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lblcosto.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        lblcosto.setText("costo");

        lblcodigo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblcodigo.setText("codigo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblsubtotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(spcantidad))
                    .addComponent(lblcosto))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblnombre)
                            .addComponent(spcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblcosto)
                            .addComponent(lblcodigo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblsubtotal))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void spcantidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spcantidadStateChanged
        int nuevaCantidad = (int) spcantidad.getValue();

        if (nuevaCantidad <= 0) {
            Carrito.quitar(item);
        } else {
            Carrito.quitar(item); 
            Carrito.agregar(new ItemCarrito(item.getProducto(), nuevaCantidad));
        }
        cotizacion.cargarProductos();
        view.mostrarItems();
    }//GEN-LAST:event_spcantidadStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblcodigo;
    private javax.swing.JLabel lblcosto;
    private javax.swing.JLabel lblimagen;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lblsubtotal;
    private javax.swing.JSpinner spcantidad;
    // End of variables declaration//GEN-END:variables
}
