package sistemacrud_dsiii_examen_final;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingUtilities;

public final class ViewCarrito extends javax.swing.JPanel {

    private final JPanel panelItems;
       
    public ViewCarrito() {
        initComponents();

        panelItems = new JPanelGradient2();
        panelItems.setLayout(new BoxLayout(panelItems, BoxLayout.Y_AXIS));
        panelItems.setPreferredSize(new Dimension(260, 1000)); // altura mayor si hay varios ítems
        panelItems.setBorder(BorderFactory.createEmptyBorder(2, 2, 2, 2));

        JScrollPane scroll = new JScrollPane(panelItems);
        scroll.getVerticalScrollBar().setUnitIncrement(16);
        scroll.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);

        jPanel2.setLayout(new BorderLayout());
        jPanel2.add(scroll, BorderLayout.CENTER);

        mostrarItems(); // Agrega los items al panel
        panelItems.revalidate();
        panelItems.repaint();
}
    
    public class JPanelGradient2 extends JPanel {    
        @Override
    
        protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g;
        int w = getWidth();
        int h = getHeight();

        Color color1 = new Color(255,228,132);
        Color color2 = new Color(255,255,255); 
        Color color3 = new Color(102,102,102);

        GradientPaint gp1 = new GradientPaint(0, 0, color1, 0, h / 2, color2);
        g2d.setPaint(gp1);
        g2d.fillRect(0, 0, w, h / 2);
        
        GradientPaint gp2 = new GradientPaint(0, h / 2, color2, 0, h, color3);
        g2d.setPaint(gp2);
        g2d.fillRect(0, h / 2, w, h);
    
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanelGradient2();
        bttndetalle = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        subtotal = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 0, new java.awt.Color(102, 102, 102)));
        jPanel1.setFocusable(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bttndetalle.setBackground(new java.awt.Color(255, 206, 133));
        bttndetalle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bttndetalle.setForeground(new java.awt.Color(102, 102, 102));
        bttndetalle.setText("Ver detalle");
        bttndetalle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttndetalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bttndetalleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bttndetalleMouseExited(evt);
            }
        });
        bttndetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttndetalleActionPerformed(evt);
            }
        });
        jPanel1.add(bttndetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, -1, -1));

        jPanel2.setBackground(new java.awt.Color(245, 245, 245));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 0, new java.awt.Color(102, 102, 102)));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 490));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 460));

        subtotal.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        subtotal.setForeground(new java.awt.Color(255, 255, 255));
        subtotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        subtotal.setText("Subtotal:");
        subtotal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jPanel1.add(subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bttndetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttndetalleActionPerformed
        if (Carrito.getItems() == null || Carrito.getItems().isEmpty()) {        
            javax.swing.JOptionPane.showMessageDialog(this, "El carrito está vacío.");        
            return;
        }
        Cotizacion cotizar = new Cotizacion(this);
        cotizar.setDefaultCloseOperation(Cotizacion.DISPOSE_ON_CLOSE);
        cotizar.setVisible(true);
    }//GEN-LAST:event_bttndetalleActionPerformed

    private void bttndetalleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttndetalleMouseExited
        bttndetalle.setBackground(new java.awt.Color(255,206,133));
        bttndetalle.setForeground(new java.awt.Color(102,102,102));
    }//GEN-LAST:event_bttndetalleMouseExited

    private void bttndetalleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttndetalleMouseEntered
        bttndetalle.setBackground(Color.GRAY);
        bttndetalle.setForeground(Color.white);
    }//GEN-LAST:event_bttndetalleMouseEntered
    
    public void mostrarItems() {    
        panelItems.removeAll();
    
        for (ItemCarrito item : Carrito.getItems()) {       
            panelItems p = new panelItems(item, this);
            p.setAlignmentX(Component.LEFT_ALIGNMENT);        
            p.setMaximumSize(new Dimension(Integer.MAX_VALUE, p.getPreferredSize().height));
            
            panelItems.add(p);
            panelItems.add(Box.createRigidArea(new Dimension(0, 5)));   
        }            
        SwingUtilities.invokeLater(() -> {    
            panelItems.revalidate();    
            panelItems.repaint();
        });    
        actualizarTotal();
    }
   
    public void actualizarTotal() {
        double total = 0.0;
        for (ItemCarrito item : Carrito.getItems()) {
            total += item.getSubtotal();   
        }       
        subtotal.setText(String.format("Subtotal: $%.2f", total));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttndetalle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel subtotal;
    // End of variables declaration//GEN-END:variables
}
